### ISSUE TITLE
KiCAD Symbol and Footprint

### ISSUE THREAD

**Issue by minkione** [wuxx/USB-HS-Bridge#3]
Hi, do you maybe have to share the CH347T symbol and footprint compatible with KiCAD?
I asked WCH, but got ignored...
Xie xie :)
P.S. Happy New Year!

**Comment by wuxx** [comment]
hello, The package of CH347 is not special, it is a common TSSOP20 package, the pin spacing is 0.65mm, WCH provice the footprint lib in AD format, can check here https://www.wch.cn/downloads/SCHPCB_ZIP.html
