### ISSUE TITLE
Schematics of 1.8V adapter board

### ISSUE THREAD

**Issue by i-c-o-n** [wuxx/USB-HS-Bridge#5]
Hi, just noticed there's a 1.8V adapter board available now. Are schematics for it available?

**Comment by wuxx** [comment]
Hello, it has been commited.

**Comment by wuxx** [comment]
Oh, sorry, there was a problem with my network. I have resubmitted it.

**Comment by wuxx** [comment]
https://github.com/wuxx/USB-HS-Bridge/blob/master/hardware/ExtBoard.pdf

**Comment by i-c-o-n** [comment]
Very nice, thank you!
