### ISSUE TITLE
请求增加封装或板子尺寸

### ISSUE THREAD

**Issue by LXY1226** [wuxx/USB-HS-Bridge#7]
请求增加板子封装，已经购买ch347f版本，想糊一个扩展板来烧录bios，尺寸自己量的总觉得强迫症，请求增加简单描述尺寸和接插件位置或封装

**Comment by wuxx** [comment]
![image](https://github.com/user-attachments/assets/cdb8316b-129f-43cd-9b84-18f60b179770)

**Comment by wuxx** [comment]
![image](https://github.com/user-attachments/assets/02bf2900-34b6-449c-a9b8-fee0f75db78d)
1620 mil x 820 mil
